version: '3.8'
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian_notes_service_clean
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - "3030:8080"
    restart: unless-stopped